### ISSUE TITLE
Add prettier to repo

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/one-fits-all#2]
Add prettier to the repo, maybe even to the flavor itself
If added to the flavor, it's best to just have a npm run format command.
The user can then add a git hook if wanted

**Comment by SteveALee** [comment]
Adding for future reference-

There is an [VSCode extension](https://github.com/prettier/prettier-vscode) which also has an option to prettify on file save. That's what I use. It's amazing how much time you save and it's a life saver for rubbish typists like myself. :)

To avoid classes with TSLint rules it's best to remove all formating rules from TSLint and let Prettier do it's stuff. There's a TSLint plugin for that too!
