### ISSUE TITLE
Does this setup typescript jsx setup support hooks?

### ISSUE THREAD

**Issue by danielchappell** [cyclejs-community/one-fits-all#29]
I haven't been able to find any examples of this jsx pipeline and how snabbdom hooks are written. I feel like I have been searching everywhere. The Cycle docs still say to use babel. Is this part of snabbdom (hooks) usable with one-fits-all transpilation pipeline? If so could we have a small example or a link to the documentation I am missing. I know this isn't a help forum, thanks in advance!

**Comment by jvanbruegge** [comment]
In general you can use `<XX module-key={value}` to access snabbdom modules. This should also include hooks, so to use an inserr hook you can do `<div hook-insert={ myHookFn } />` (I have not tested this, but should work)

**Comment by danielchappell** [comment]
It seems to work! Thank you!
