### ISSUE TITLE
Dev server does not work for 2+ level routes

### ISSUE THREAD

**Issue by baranovxyz** [cyclejs-community/one-fits-all#48]
export const routes: Routes = {
  "/": { component: Counter, scope: "counter" },
  "/p2/main":  { component: Speaker, scope: "speaker" },
};

"/p2/main" route does not work if I input it directly in browser
though it obviously does work if I follow it from main page.

The reason is simple:
main:9 GET http://localhost:8080/p2/bundle.91c2e2b0e949aa717548.js?91c2e2b0e949aa717548 net::ERR_ABORTED

Browser asks for bundle at /p2/bunde... while it is at /bundle...

**Comment by jvanbruegge** [comment]
Released in `5.1.0`
