### ISSUE TITLE
"Warning: Cannot read property 'flags' of undefined" when building

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/one-fits-all#6]
_From @SteveALee on July 20, 2017 9:10_

This turns out to be a TSLint issue (it doesn't prefix warnings) and there is an [open issue](https://github.com/palantir/tslint/issues/2876) tracking it.

For me the warning is caused by TSLint rule `no-use-before-declare` but issue indicates it also happens with `no-unused-variable`

_Copied from original issue: cyclejs-community/create-cycle-app-flavors#40_

**Comment by SteveALee** [comment]
Looks like they [merged a fix](https://github.com/palantir/tslint/pull/3058)

**Comment by jvanbruegge** [comment]
Is this fixed then?

**Comment by SteveALee** [comment]
Is this fixed then?

Last release was 5th July so I guess not yet

**Comment by jvanbruegge** [comment]
the next version should be released this week

**Comment by jvanbruegge** [comment]
Closing this now as I had no further issues, reopen if you have them
