### ISSUE TITLE
Tests Fail to Compile After a Clean Install of Version 5.2.0

### ISSUE THREAD

**Issue by danielyogel** [cyclejs-community/one-fits-all#62]
Hi,

Step to reproduce:

1. `npm install -g create-cycle-app`
2. `create-cycle-app myAppName --flavor cycle-scripts-one-fits-all`
3. `cd myAppName `
4. `npm run start`

Result: 
`webpack: Compiled successfully.

**[at-loader] Checking finished with 10 errors**
[at-loader] ./test/app.test.ts:42:23
    TS2322: Type 'MemoryStream<boolean>' is not assignable to type 'Stream<boolean>'.
  Property '_ils' is protected but type 'Stream<T>' is not a class derived from 'Stream<T>'.
`

Thanks !

Note: I'm using npm 5.5.1,  Node 8.91 and create-cycle-app 4.0.0

**Comment by jvanbruegge** [comment]
This is very weird, because i tested that. But I might have an idea

**Comment by danielyogel** [comment]
Maybe I've done something wrong... :) Trying to understand too, Thanks again.

**Comment by jvanbruegge** [comment]
Sorry it took so long, totally forgot about this issue. Is fixed now in the latest release
