### ISSUE TITLE
Can't update packages' versions.

### ISSUE THREAD

**Issue by zheeeng** [cyclejs-community/one-fits-all#94]
After creating a new project, cd into the project directory and yarn install cause starting failure.

**Comment by zheeeng** [comment]
Seems the latest version TypeScript causes this problem.

**Comment by zheeeng** [comment]
I use `create-cycle-app my-awesome-cyclejs --flavor cycle-scripts-one-fits-all --yarn`, this command installs typescript@2.9.2 automatically.

**Comment by jvanbruegge** [comment]
I failed to fix the typescript version to `2.8`. I will fix that

**Comment by jvanbruegge** [comment]
Done now
