### ISSUE TITLE
npm start fails at `cycle-scripts start`

### ISSUE THREAD

**Issue by binarybro** [cyclejs-community/one-fits-all#97]
On my Windows machine, `npm start` fails at `cycle-scripts start`:

```
C:\Users\---------\WebstormProjects\cycle-attack>npm start

> cycle-attack@0.1.0 start C:\Users\---------\WebstormProjects\cycle-attack
> cycle-scripts start

The system cannot find the path specified.
```

Created using `create-cycle-app cycle-attack --flavor cycle-scripts-one-fits-all@6.0.1`

Switching to yarn fails with the same message.
Created using `create-cycle-app cycle-attack --flavor cycle-scripts-one-fits-all@6.0.1 --yarn`

```
node@10.10
npm@6.4.1
create-cycle-app@5 (also fails with @4)
cycle-scripts-one-fits-all@6.0.1
Microsoft Windows 10 Pro 10.0.17763 N/A Build 17763
```

**Comment by binarybro** [comment]
Okay, I found the issue is in `scripts/start.js`. I'll fix it and open a PR.

**Comment by binarybro** [comment]
Fixed in this PR (not tested yet, going to lunch now): https://github.com/cyclejs-community/one-fits-all/pull/98

**Comment by jvanbruegge** [comment]
Released the new version on npm, enjoy your vacation :)
